name: IndigoRPG
version: '1.0-SNAPSHOT'
main: me.flyingtaco725.indigorpg.IndigoRPG
api-version: '1.21'

commands:
  char:
    description: IRPG Commands
    usage: /<command>
    permission: char.use
    children:
      setname:
        description: set current character's name
        usage: /<command> setname <name>
        permission: char.setname
  dm:
    description: 'PREFIX for commands intended only for Dungeon Masters'
    usage: /<command>
    permission: dm.use
    children:
      characterCreateLocation:
        description: 'Sets the location for where created players will spawn as well as where everyone will be when selecting their character'
        usage: /<command> characterCreationLocation | /<command> charCreateLocation
        permission: dm.charactercreatelocation

permissions:
  char.use:
    description: general irpg command
    default: true
  char.setname:
    description: sets the name of your current pending character
    default: true
  dm.charactercreatelocation:
    description: sets the location for new players, and character selection screen
    default: true

## depend: [ ProtocolLib ]